# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb5fc9590da05f5979662ff855b6e44b49476efde548acb89f10ca75a84e6722a7fdbbec5a83df9765f52ca32a14a857b1be12b417140828edf2ab0c47b42cb6

test:
  secret_key_base: a331e9a77303c02d56f1d4fa501d49dd977a49c228e38780e98ce69296ccfd9f4dde7563c78fa590303affc341fc35edbf922af3b3a8dd26a41bc2aaf936489e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
